version: "3"
services:
  mongodb:
    image: "mongo"
    labels:
      com.docker.compose.description: "DB for purch formulaire"
    volumes: 
      - ../data:/data/db
    ports:
      - "27017:27017"
    networks: 
    - n-back
  backend:
    image: "node:10-alpine" #image node
    build:
      context: ../BackNode
      dockerfile: Dockerfile
    networks: 
      - n-back
    ports:
      - "3001:3001"
    # command: >
      # bash -c "mkdir -p /src/app
      # && cd /src/app
      # && copy package.json /src/app/package.json
      # && npm install"
  web:
    image: "nginx" #server web
    build:
        context: .
        dockerfile: ./Dockerfile
    # command: bash -c "copy ./build/ /usr/share/nginx/html"
    ports: 
      - "80:80"
    networks: 
      - n-front
networks:
  n-front:
  n-back:
volumes:
  data: